name: Deploy to Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun Environment
        uses: oven-sh/setup-bun@v2.0.1

      - name: Install Node.js
        uses: actions/setup-node@v4
        
      - name: Install dependencies
        run: bun install

      - name: Build application
        run: bun run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t next15-on-lambda .
          docker tag next15-on-lambda:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/next15-on-lambda:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/next15-on-lambda:latest

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name next15-on-lambda \
            --image-uri ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/next15-on-lambda:latest

      - name: Deploy static files to S3
        run: |
          aws s3 sync .next/static/ s3://next15-on-lambda-assets/_next/static/
          aws s3 cp public/ s3://next15-on-lambda-assets/ --recursive
